title = "default parameters configuration"

[parameter]

[parameter.title]
kind="meta"
type="str"
default_value="default_title"
required=true

[parameter.num_buf]
plural = "num_bufs"
kind = "param"
type = "int"
required = true
default_values = [10, 20, 30, 40, 50]
param_key = "beffers"

[parameter.num_node]
plural = "num_nodes"
kind = "network_param"
type = "int"
default_values = [10, 20, 30, 40, 50]
required = true
param_key = "numNodes"

[parameter.connection_type]
plural = "connection_types"
kind = "network_param"
required = true
param_key = "connectionType"
default_values = ["MM", "MIM"]
type = "str"
options = ["MM", "MIM"]

[parameter.traffic_pattern_index]
plural = "traffic_pattern_indices"
kind = "param"
default_values = [0,1,2]
required = true
param_key = "app.TrafficPattern"
type = "int"

[parameter.link_tomography_enabled]
plural = "link_tomography_enabled_list"
kind = "param"
default_values = [false, true]
required = true
param_key = "qrsa.hm.link_tomography"
type = "bool"

[parameter.num_purification_iteration]
plural = "num_purification_iterations"
kind = "param"
default_values = [0]
required = true
param_key = "qrsa.hm.initial_purification"
type = "int"

[parameter.purification_type]
plural = "purification_types"
kind = "param"
default_values = [1001]
required = true
param_key = "qrsa.hm.purification_type"
type = "int"

[parameter.e2e_connection_enabled]
plural = "e2e_connection_enabled_list"
kind = "param"
default_values = [false]
required = true
param_key = "app.EndToEndConnection"
type = "bool"

[parameter.num_measure]
plural = "num_measures"
kind = "param"
default_values = [3000]
required = true
param_key = "qrsa.hm.num_measure"
type = "int"

[parameter.number_of_bellpair]
plural = "number_of_bellpair_list"
kind = "param"
default_values = [10]
required = true
param_key = "app.number_of_bellpair"
type = "int"

[parameter.lone_initiator_addr]
plural = "lone_initiator_addrs"
kind = "param"
default_values = [0]
required = true
param_key = "app.LoneInitiatorAddress"
type = "int"
